apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-api-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: user-auth-api
  template:
    metadata:
      labels:
        app: user-auth-api
    spec:
      containers:
        - name: tec-takehome-container
          image: <account key>.dkr.ecr.region.amazonaws.com/tec-takehome-2024:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "1"
              memory: "200Mi"
          livenessProbe:
            httpGet:
              path: /user-auth
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /user-auth
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: ecr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: user-auth-api-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: user-auth-api
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-auth-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: user-auth-api